theme: jekyll-theme-cayman
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM    

gems:
  - jemoji            
  - jekyll-mentions
<?xml version="1.0" encoding="utf-8"?>
<browserconfig>
    <msapplication>
        <tile>
            <square150x150logo src="/mstile-150x150.png"/>
            <TileColor>#da532c</TileColor>
        </tile>
    </msapplication>
</browserconfig>
